In [19]:
#1
some_list = [(10, 20), (1), (30, 56, 25), (10, 20), (33), (40), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
new_list = []
for k in range(12):
    a = sum(some_list[k])
    
    

TypeError: 'int' object is not iterable

In [30]:
#6
import numpy
Matrix_A = numpy.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19,  21, 3], [11, 18, 25, 2, 9]], dtype = float)
for i in range(len(Matrix)-1):
    coef = Matrix_A[i].mean()
    Matrix_A[i] = numpy.subtract(Matrix_A[i], coef)
print Matrix_A

[[  4.  11. -12.  -5.   2.]
 [ 10.  -8.  -6.   1.   3.]
 [ -9.  -7.   0.   7.   9.]
 [ -3.  -1.   6.   8. -10.]
 [ 11.  18.  25.   2.   9.]]


In [59]:
#7
A = numpy.array([[17, 24, 1, 8, 15], [23, 5, 7, 14, 16], [4, 6, 13, 20, 22], [10, 12, 19,  21, 3], [11, 18, 25, 2, 9]], dtype = float)
B = numpy.array([[1, 24, 1, 8, 15], [-3, 5, 7, -14, 16], [4, 6, -3, 20, 2], [10, 12, 19, 21, 3], [1, 1, 2, -2, 0]], dtype = float)
AB = numpy.array([[sum(a*b for a,b in zip(A_row,B_col)) for B_col in zip(*B)] for A_row in A], dtype = float)
AB_T = numpy.transpose(AB)
AB_T_B = numpy.array([[sum(a*b for a,b in zip(AB_T_row,B_col)) for B_col in zip(*B)] for AB_T_row in AB_T], dtype = float)
print AB_T_B

vector = 0
for i in range(5):
    for j in range(5):
        vector += (AB_T_B[i][j])**2
        AB_T_B[i] = AB_T_B[i] / (vector**0.5) 
normalized_matrix = AB_T_B
print AB_T_B


[[  3224.   6818.   5777.   8215.   5041.]
 [  7327.  30856.  18653.  16213.  25462.]
 [  5621.  18419.  10050.  15888.  13008.]
 [  8376.  14160.  16351.  18667.  10975.]
 [  5129.  25642.  12741.  11711.  19484.]]
[[  9.25591790e-15   1.95740844e-14   1.65854335e-14   2.35847908e-14
    1.44724200e-14]
 [  2.22912705e-16   9.38746337e-16   5.67488833e-16   4.93255586e-16
    7.74642184e-16]
 [  6.27798161e-17   2.05718099e-16   1.12246424e-16   1.77449870e-16
    1.45283730e-16]
 [  2.36518365e-17   3.99844800e-17   4.61713441e-17   5.27111785e-17
    3.09907957e-17]
 [  1.00229386e-17   5.01088307e-17   2.48980817e-17   2.28852865e-17
    3.80750510e-17]]


In [65]:
#8
for i in range(5):
    for j in range(5):
        if 3<B[i][j]<16:
            B[i][j] = -1*B[i][j]
print B

[[  1.  24.   1.  -8. -15.]
 [ -3.  -5.  -7. -14.  16.]
 [ -4.  -6.  -3.  20.   2.]
 [-10. -12.  19.  21.   3.]
 [  1.   1.   2.  -2.   0.]]


In [75]:
#9
vector = numpy.random.rand(1,10)
print vector.max(axis = 1)

[ 0.94618498]


In [77]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, numpy.nan, 5, 2, 4.5, numpy.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [85]:
#8.1, 8.2
df = pd.DataFrame(data, labels)
print type(df)
df

<class 'pandas.core.frame.DataFrame'>


age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h  NaN    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1

In [86]:
#8.3
df.head(5)

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2

In [93]:
#8.4
df.iloc[:, [1, 0]]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [94]:
#8.5
df.iloc[[1,3,5], [1,0]]

animal  age
b    cat  3.0
d    dog  NaN
f    cat  2.0